---
- name: Bootstrap Signoz
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check Docker Compose version
      command: docker-compose --version
      register: docker_compose_version
      changed_when: false

    - name: Show Docker Compose version
      debug:
        msg: "{{ docker_compose_version.stdout }}"

    - name: Bootstrap Signoz using Docker Compose
      community.docker.docker_compose_v2:
        project_src: "."
        state: present
        pull: always          # This ensures it always pulls the latest images
        recreate: auto        # Automatically recreate containers if necessary
        remove_orphans: true  # Remove containers that are no longer part of the Compose file
        ignore_build_events: true
        dependencies: true
